### PR TITLE
Private

### PR DESCRIPTION
**Pull request by nimma0001**

### CODE REVIEW

**Comment by gautamajay52** [comment]
First don't do this like pull request to main repo...

And last.... changing seed time is not going to seed the file 😜🤣

Bettter buy a seedbox.
And also don't do this...this may cause heroku to ban this repo

**Comment by nimma0001** [comment]
Sport already using it and uploaded 189gb as seeder and I also changed some line to work with private torrent they ban this software Aria2c

**Comment by nimma0001** [comment]
I know when there is leech file will get seeded and file will not be uploaded in group until time complete or I need to do leach comad agin to get it before finish time

**Comment by nimma0001** [comment]
Thanks u awesome work btw

**Pull request closed without merging**
